clc;
clear all; 
videoName = '06-brzoZaklanjanje';
fileID1 = fopen(strcat(strcat('..\BenchmarkResults\Results', videoName),'.mp4boostingMETRIKA2HSV.txt'),'r');
fileID2 = fopen(strcat(strcat('..\BenchmarkResults\Results', videoName),'.mp4csrtMETRIKA2HSV.txt'),'r');
fileID3 = fopen(strcat(strcat('..\BenchmarkResults\Results', videoName),'.mp4kcfMETRIKA2HSV.txt'),'r');
fileID4 = fopen(strcat(strcat('..\BenchmarkResults\Results', videoName),'.mp4medianflowMETRIKA2HSV.txt'),'r');
fileID5 = fopen(strcat(strcat('..\BenchmarkResults\Results', videoName),'.mp4milMETRIKA2HSV.txt'),'r');
fileID6 = fopen(strcat(strcat('..\BenchmarkResults\Results', videoName),'.mp4mosseMETRIKA2HSV.txt'),'r');
fileID7 = fopen(strcat(strcat('..\BenchmarkResults\Results', videoName),'.mp4tldMETRIKA2HSV.txt'),'r');

formatSpec = '%f';
boosting = fscanf(fileID1, formatSpec);
csrt = fscanf(fileID2, formatSpec);
kcf = fscanf(fileID3, formatSpec);
medianflow = fscanf(fileID4, formatSpec);
mil = fscanf(fileID5, formatSpec);
mosse = fscanf(fileID6, formatSpec);
tld = fscanf(fileID7, formatSpec);
brojRedova = size(boosting, 1);
t = 1:brojRedova;
plot(t, boosting, 'DisplayName','boosting');
hold on;
plot(t, csrt,  'DisplayName','csrt');
plot(t, kcf,  'DisplayName','kcf');
plot(t, medianflow,  'DisplayName','medianflow');
plot(t, mil,  'DisplayName','mil');
plot(t, mosse,  'DisplayName','mosse');
plot(t, tld,  'DisplayName','tld');
legend
xlabel('Frame');
ylabel('Maximum Success Rate');
title('Benchmark results for each algorithm with HSV comparison - Maximum Success Rate');
hold off;
fclose(fileID1);
fclose(fileID2);
fclose(fileID3);
fclose(fileID4);
fclose(fileID5);
fclose(fileID6);
fclose(fileID7);